config/urls.py
from django.conf import settings
from django.conf.urls import include, url, handler400, handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

from proj.users import views

urlpatterns = [
                  url(r'^$', views.home_view, name='home'),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                  url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),

                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, admin.site.urls),

                  url(r'^users/', include('proj.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  url(r'^t/', include('proj.t.urls', namespace='t')),
                  url(r'^s/', include('proj.s.urls', namespace='s')),
                  url(r'^error/$', views.error_view, name='error-page'),
                  url(r'^info/$', views.info_view, name='info-page'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}, name='e-400'),
    url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}, name='e-403'),
    url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}, name='e-404'),
    url(r'^500/$', default_views.server_error, name='e-500'),
]

handler400 = views.error_400
handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

proj/s/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        # /s/
        regex=r'^$',
        view=views.index_view,
        name='studenthome'
    ),
    url(
        # /s/question/list/all/
        regex=r'^question/list/all/$',
        view=views.QuestionsListView.as_view(),
        name='question-list-all'
    ),
    url(
        # /s/answer/createforquestion/(?P<pk>[0-9]+)/
        regex=r'^answer/createforquestion/(?P<pk>[0-9]+)/$',
        view=views.AnswerCreateView.as_view(),
        name='answer-createforquestion'
    ),
    url(
        # /s/test/list/all/
        regex=r'^test/list/all/$',
        view=views.TestListView.as_view(),
        name='test-list-all'
    ),
    url(
        # /s/answer/list/my/
        regex=r'^answer/list/my/$',
        view=views.answer_list_view,
        name='answer-list-my'
    ),
    url(
        # /s/testandquestion/search/tnameorid/
        regex=r'^testandquestion/search/tnameorid/$',
        view=views.search_test_and_question_by_teacher_name_or_id,
        name='test-and-question-search-by-teachernameorid'
    ),
    url(
        # /s/test/(?P<pk>[0-9]+)/
        regex=r'^test/(?P<pk>[0-9]+)/$',
        view=views.test_x,
        name='test-x'
    ),
]

proj/t/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        # /t/
        regex=r'^$',
        view=TemplateView.as_view(template_name='t/teacher_index.html'),
        name='teacherhome'
    ),
    url(
        # /t/test/new/
        regex=r'^test/new/$',
        view=views.TestCreateView.as_view(),
        name='test-new'
    ),
    url(
        # /t/test/update/(?P<pk>[0-9]+)/
        regex=r'^test/update/(?P<pk>[0-9]+)/$',
        view=views.TestUpdateView.as_view(),
        name='test-update'
    ),
    url(
        # /t/test/delete/(?P<pk>[0-9]+)/
        regex=r'^test/delete/(?P<pk>[0-9]+)/$',
        view=views.TestDeleteView.as_view(),
        name='test-delete'
    ),
    url(
        # /t/test/list/
        regex=r'^test/list/$',
        view=views.TestListView.as_view(),
        name='test-list'
    ),
    url(
        # /t/test/all/list/
        regex=r'^test/all/list/$',
        view=views.TestAllListView.as_view(),
        name='test-all-list'
    ),
    url(
        # /t/question/new/
        regex=r'^question/new/$',
        view=views.QuestionConceptRefAnsCreate.as_view(),
        name='question-new'
    ),
    url(
        # /t/question/update/(?P<pk>[0-9]+)/
        regex=r'^question/update/(?P<pk>[0-9]+)/$',
        view=views.QuestionConceptRefAnsUpdate.as_view(),
        name='question-update'
    ),
    url(
        # /t/question/listbytest/(?P<pk>[0-9]+)/
        regex=r'^question/listbytest/(?P<pk>[0-9]+)/$',
        view=views.QuestionByTestListView.as_view(),
        name='question-list-by-test'
    ),
    url(
        # /t/question/details/(?P<pk>[0-9]+)/
        regex=r'^question/details/(?P<pk>[0-9]+)/$',
        view=views.QuestionDetailView.as_view(),
        name='question-details'
    ),
    url(
        # /t/question/delete/(?P<pk>[0-9]+)/
        regex=r'^question/delete/(?P<pk>[0-9]+)/$',
        view=views.QuestionDeleteView.as_view(),
        name='question-delete'
    ),
    url(
        # /t/concept/add/(?P<pk>[0-9]+)/
        regex=r'^concept/add/(?P<pk>[0-9]+)/$',
        view=views.ConceptCreateView.as_view(),
        name='concept-add'
    ),
    url(
        # /t/refans/add/(?P<pk>[0-9]+)/
        regex=r'^refans/add/(?P<pk>[0-9]+)/$',
        view=views.RefAnsCreateView.as_view(),
        name='refans-add'
    ),
    url(
        # /t/question/answersgrading/(?P<pk>[0-9]+)/
        regex=r'^question/answersgrading/(?P<pk>[0-9]+)/$',
        view=views.question_answersgrading,
        name='question-answersgrading'
    ),
    url(
        # /t/question/(?P<pk>[0-9]+)/answers/
        regex=r'^question/(?P<pk>[0-9]+)/answers/$',
        view=views.AnswerListView.as_view(),
        name='answers-list'
    ),
]

proj/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.after_login_view,
        name='redirect'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.after_login_view,
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~chooseusertype/$',
        view=views.choose_user_type,
        name='chooseusertype'
    ),
    url(
        regex=r'^~studentsignup/$',
        view=views.StudentCreateView.as_view(),
        name='studentsignup'
    ),
    url(
        regex=r'^~teachersignup/$',
        view=views.TeacherCreateView.as_view(),
        name='teachersignup'
    ),
    url(
        regex=r'^~studentupdate/$',
        view=views.StudentUpdateView.as_view(),
        name='studentupdate'
    ),
    url(
        regex=r'^~teacherupdate/$',
        view=views.TeacherUpdateView.as_view(),
        name='teacherupdate'
    ),
]

proj/s/models.py
from django.contrib.auth.models import AbstractUser

proj/s/forms.py
from django import forms
from django.forms import ModelForm

from proj.t.models import Answer


class SearchTestOrQuestionByTeacherNameOrId(forms.Form):
    nome = forms.CharField(required=False, label='Nome do Professor')
    idd = forms.IntegerField(required=False, label='Id do Professor')


class AnswerForm(ModelForm):
    question_iddd = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = Answer
        fields = ['answer_text']
        widgets = {
            'answer_text': forms.Textarea(attrs={'class': "textarea form-control", 'rows': 5})
        }

proj/s/views.py
import pickle
from collections import defaultdict

import numpy as np

from proj.autograde import extract_all as eall
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.forms import formset_factory
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView

from proj.s.forms import AnswerForm
from proj.t.models import Question, Answer, Test, ReferenceAnswer
from proj.s import forms


def convert_to_binary(num):
    if num == 0 or num == 1:
        return 0
    elif num == 2 or num == 3:
        return 1


class QuestionsListView(LoginRequiredMixin, ListView):
    model = Question
    template_name = 's/question_list.html'

    def get_queryset(self):
        return Question.objects.filter(~Q(answers__user=self.request.user))


class AnswerCreateView(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text']
    template_name = 's/answer_form.html'

    def get_success_url(self):
        return reverse('s:question-list-all')

    def get_context_data(self, **kwargs):
        context = super(AnswerCreateView, self).get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_invalid(self, form):
        messages.error(self.request, 'Ocorreu um erro no cadastro da resposta!')
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.info(self.request, 'O cadastro da resposta foi realizado com sucesso!')
        form.instance.user = self.request.user
        pkk = self.kwargs['pk']
        form.instance.question = Question.objects.get(pk=pkk)
        # --------------------------------------------------------------------------
        try:
            ref_ans_list = ReferenceAnswer.objects.filter(question_id=pkk)
            ras_dict = defaultdict(list)
            for ra in ref_ans_list:
                ras_dict[pkk].append(ra.ref_ans_text)
            spc_ref_anss = ras_dict[pkk]

            ans_text = form.cleaned_data['answer_text']

            clf = pickle.load(open("proj/autograde/models/m_" + str(pkk) + ".pkl", 'rb'))
            cv1 = pickle.load(open("proj/autograde/models/cv1_" + str(pkk) + ".pkl", 'rb'))
            cv2 = pickle.load(open("proj/autograde/models/cv2_" + str(pkk) + ".pkl", 'rb'))

            X_lexsim = eall.get_lex_feats(ans_text, spc_ref_anss)
            xboww = eall.get_ngrams(cv1, cv2, [ans_text])
            X_tslda = eall.get_ts_lda_feats([ans_text], xboww)
            X_wnsim = eall.get_wn_feats(ans_text, spc_ref_anss)

            X = np.append(xboww, X_lexsim)
            X = np.append(X, X_wnsim)
            X = np.append(X, X_tslda)
            X = np.array([X])
            pred = clf.predict(X)

            form.instance.a_grade = pred[0]
            form.instance.a_bin_grade = convert_to_binary(pred[0])
        except FileNotFoundError:
            print("FILE NOT FOUND, MODEL NOT YET TRAINED")
        # --------------------------------------------------------------------------
        return super().form_valid(form)


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    template_name = 's/test_list.html'


class AnswerListView(LoginRequiredMixin, ListView):
    model = Answer
    template_name = 's/answer_list.html'

    def get_queryset(self):
        return Answer.objects.filter(user=self.request.user)


def bin_mean(bin_list, teacher_bin):
    if len(bin_list) == 0:
        return None
    if len(bin_list) % 2 == 0:
        bin_list.append(teacher_bin)
    return max(set(bin_list), key=bin_list.count)


@login_required
def answer_list_view(request):
    if request.method == 'GET':
        answers = Answer.objects.filter(user=request.user)
        object_list = []
        for a in answers:
            other_grades = a.grades.all()
            if len(other_grades) > 0:
                media = 0
                bin_ot_grades = [og.ot_bin_grade for og in other_grades]
                for og in other_grades:
                    media += og.ot_grade
                media /= len(other_grades)
                if a.t_grade is not None:
                    mean_overall = (media * len(other_grades) + a.t_grade) / (1 + len(other_grades))
                else:
                    mean_overall = None
            else:
                bin_ot_grades = []
                media = None
                mean_overall = None
            new_ans = {
                'mean_overall': mean_overall,
                'mean_other_teachers': media,
                'mean_bin_overall': bin_mean(bin_ot_grades, a.t_bin_grade),
                'question_statement': a.question.statement,
                'answer_text': a.answer_text,
                't_grade': a.t_grade,
                't_bin_grade': a.t_bin_grade,
                'a_grade': a.a_grade,
                'a_bin_grade': a.a_bin_grade,
            }
            object_list.append(new_ans)
        return render(request, 's/answer_list.html', {'object_list': object_list})


@login_required
def search_test_and_question_by_teacher_name_or_id(request):
    if request.method == 'POST':
        if 'test' in request.POST:
            form = forms.SearchTestOrQuestionByTeacherNameOrId(request.POST)
            if form.is_valid():
                if form.cleaned_data['idd'] is None:
                    form.cleaned_data['idd'] = ''
                if form.cleaned_data['idd'] == '' and form.cleaned_data['nome'] == '':
                    tests = Test.objects.none()
                elif form.cleaned_data['idd'] != '' and form.cleaned_data['nome'] == '':
                    tests = Test.objects.filter(user__pk=form.cleaned_data['idd'])
                elif form.cleaned_data['idd'] == '' and form.cleaned_data['nome'] != '':
                    tests = Test.objects.filter(user__ass_teacher__nome__icontains=form.cleaned_data['nome'])
                elif form.cleaned_data['idd'] != '' and form.cleaned_data['nome'] != '':
                    tests = Test.objects.filter(
                        Q(user__pk=form.cleaned_data['idd']),
                        Q(user__ass_teacher__nome__icontains=form.cleaned_data['nome'])
                    )
                else:
                    tests = Test.objects.none()
            else:
                tests = Test.objects.none()
            return render(request, 's/test_list.html', {'object_list': tests})
        elif 'question':
            form = forms.SearchTestOrQuestionByTeacherNameOrId(request.POST)
            if form.is_valid():
                if form.cleaned_data['idd'] is None:
                    form.cleaned_data['idd'] = ''
                if form.cleaned_data['idd'] == '' and form.cleaned_data['nome'] == '':
                    questions = Question.objects.none()
                elif form.cleaned_data['idd'] != '' and form.cleaned_data['nome'] == '':
                    questions = Question.objects.filter(
                        ~Q(answers__user=request.user),
                        Q(user__pk=form.cleaned_data['idd'])
                    )
                elif form.cleaned_data['idd'] == '' and form.cleaned_data['nome'] != '':
                    questions = Question.objects.filter(
                        ~Q(answers__user=request.user),
                        Q(user__ass_teacher__nome__icontains=form.cleaned_data['nome'])
                    )
                elif form.cleaned_data['idd'] != '' and form.cleaned_data['nome'] != '':
                    questions = Question.objects.filter(
                        ~Q(answers__user=request.user),
                        Q(user__pk=form.cleaned_data['idd']),
                        Q(user__ass_teacher__nome__icontains=form.cleaned_data['nome'])
                    )
                else:
                    questions = Question.objects.none()
            else:
                questions = Question.objects.none()
            return render(request, 's/question_list.html', {'object_list': questions})


@login_required
def index_view(request):
    form = forms.SearchTestOrQuestionByTeacherNameOrId()
    return render(request, 's/student_index.html', {'form': form})


@login_required
def test_x(request, pk):
    AnswerFormSet = formset_factory(AnswerForm, extra=1)

    if request.method == 'GET':
        questions = Question.objects.filter(
            ~Q(answers__user=request.user),
            Q(test_id=pk)
        )
        questions_id_list = [{'question_iddd': q.id} for q in questions]
        test_formset = AnswerFormSet(initial=questions_id_list)

        return render(request, 's/test.html', {
            'test_formset': test_formset,
            'questions': questions
        })
    elif request.method == 'POST':
        test_formset = AnswerFormSet(request.POST)

        questions = Question.objects.filter(
            ~Q(answers__user=request.user),
            Q(test_id=pk)
        )
        answers_list = []

        if test_formset.is_valid():
            for f in test_formset[0:len(test_formset)-1]:
                new_answer = Answer()
                new_answer.answer_text = f.cleaned_data.get('answer_text', 'erro')
                for q in questions:
                    if q.id == f.cleaned_data.get('question_iddd', 'erro'):
                        new_answer.question = q
                new_answer.user = request.user
                if new_answer.answer_text != '':
                    answers_list.append(new_answer)
            Answer.objects.bulk_create(answers_list)
            messages.info(request, 'Suas respostas para a prova foram cadastradas com sucesso!')
            return redirect(reverse('s:test-list-all'))
        else:
            messages.error(request, "Ocorreu um erro no cadastro das suas respostas! "

proj/templates/t/answer_list.html
{% extends "account/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Respostas da Questão{% endblock %}
{% block speccss %}
    <link href="{% static 'css/answer_list.css' %}" rel="stylesheet">
{% endblock %}

{% block inner %}

    <h1 class="h1-styled">Respostas da Questão</h1>

    <div class="container-ql">

        <div class="element">
            <h3>Questão</h3>
            <h6 class="text-capitalize">{{ object_list.0.question.statement }}</h6>
        </div>

        <div class="element">
            <h3>Respostas</h3>
            <ul class="list-group">
                {% for a in object_list %}
                    <li class="list-group-item">{{ a.answer_text }}</li>
                {% empty %}
                    <li class="list-group-item">Nenhuma resposta de alunos para essa questão.</li>
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}

proj/templates/t/concept_form.html
{% extends "account/base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Adicionar Conceito{% endblock %}

{% block inner %}

    <h1 class="h1-styled">Adicionar Conceito</h1>

    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>

{% endblock %}

proj/templates/t/grade_answer.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Avaliar Resposta{% endblock %}
{% block speccss %}
    <link href="{% static 'css/grade_answer.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <h1 class="h1-styled">Avaliar resposta</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="container-ga">

                {% if request.session.answers_for_question_x_dict_list|length|add:-1 > 0 %}
                    <h4>Falta avaliar mais <span class="badge badge-secondary">{{ request.session.answers_for_question_x_dict_list|length|add:-1 }}</span> respostas além dessa.</h4>
                {% else %}
                    <h4>Essa é a última resposta!</h4>
                {% endif %}

                <div class="element">
                    <h5><strong>Questão</strong></h5>
                    <h6 class="text-capitalize">{{ request.session.answers_for_question_x_dict_list.0.question_statement }}</h6>
                </div>

                <div class="element">
                    <h5><strong>Resposta</strong></h5>
                    <h6>{{ request.session.answers_for_question_x_dict_list.0.answer_text }}</h6>
                </div>

                <form action="{% url 't:question-answersgrading' pk=request.session.answers_for_question_x_dict_list.0.question_id %}" method="POST">
                    <div class="element binario_invisivel">
                        {{ form.t_bin_grade.errors }}
                        <label for="{{ form.t_bin_grade.id_for_label }}" class="h5 h5-styled"><strong>Nota Binária</strong></label>
                        <br>
                        {{ form.t_bin_grade }}
                    </div>

                    <div class="element">
                        {{ form.t_grade.errors }}
                        <label for="{{ form.t_grade.id_for_label }}" class="h5 h5-styled"><strong>Nota</strong></label>
                        <br>
                        {{ form.t_grade }}
                    </div>

                    {% csrf_token %}

                    <button type="submit" class="btn btn-primary" name="terminar">Avaliar e Terminar</button>
                    {% if request.session.answers_for_question_x_dict_list|length > 1 %}
                        <button type="submit" class="btn btn-secondary" name="continuar">Avaliar e Continuar</button>
                    {% endif %}
                </form>

            </div>
        </div>
        <div class="col-md-6 offset-md-3 lado2">
            <h4 class="element element2">Conceitos envolvidos:</h4>
            <ul class="list-group">
                {% for concept in concepts %}
                    <li class="list-group-item">{{ concept.concept_text }}</li>
                {% empty %}
                    <li class="list-group-item">Nenhum conceito cadastrado para a questão.</li>
                {% endfor %}
            </ul>
            <h4 class="element element2">Respostas de Referência:</h4>
            <ul class="list-group">
                {% for ref_a in ref_ans %}
                    <li class="list-group-item">{{ ref_a.ref_ans_text }}</li>
                {% empty %}
                    <li class="list-group-item">Nenhuma resposta de referência cadastrada para a questão.</li>
                {% endfor %}
            </ul>
        </div>
    </div>



{% endblock %}

proj/templates/t/question_detail.html
{% extends "account/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Detalhes da Questão{% endblock %}
{% block speccss %}
    <link href="{% static 'css/question_detail.css' %}" rel="stylesheet">
{% endblock %}

{% block inner %}

    <h1 class="h1-styled">Detalhes da Questão</h1>

    <div class="container-ql">

        <div class="element">
            <h3>Prova</h3>
            <h6 class="text-capitalize">{{ question.test.name }}</h6>
        </div>

        <div class="element">
            <h3>Enunciado</h3>
            <h6>{{ question.statement }}</h6>
        </div>

        <div class="element">
            <h3>Conceitos</h3>
            <ul class="list-group">
                {% for concept in question.concepts.all %}
                    <li class="list-group-item">{{ concept.concept_text }}</li>
                {% empty %}
                    <li class="list-group-item">Nenhum conceito nessa questão.</li>
                {% endfor %}
            </ul>
            <a href="{% url 't:concept-add' pk=question.pk %}">Adicionar conceito</a>
        </div>

        <div class="element">
            <h3>Respostas de Referência</h3>
            <ul class="list-group">
                {% for refans in question.ref_answers.all %}
                    <li class="list-group-item">{{ refans.ref_ans_text }}</li>
                {% empty %}
                    <li class="list-group-item">Nenhuma resposta de referência para a questão.</li>
                {% endfor %}
            </ul>
            <a href="{% url 't:refans-add' pk=question.pk %}">Adicionar resposta de referência</a>
        </div>

    </div>

{% endblock %}

proj/templates/t/question_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Questões{% endblock %}
{% block speccss %}
    <link href="{% static 'css/question_list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <h1 class="h1-styled">Questões da Prova</h1>

    <div class="question-list">
    {% for q in object_list %}
        <div class="row">
            <div class="col-md-9">
                <div class="three-parts">
                    <div class="statement">
                        <h4>{{ q.statement }}</h4>
                        {% if request.user.is_superuser %}
                            <a href="{% url 't:question-update' pk=q.pk %}">Editar</a> |
                            <a href="{% url 't:question-delete' pk=q.pk %}">Excluir</a> |
                        {% endif %}
                    </div>
                    <div class="details">
                        <a href="{% url 't:question-details' pk=q.pk %}">
                            <figure>
                                <img src="{% static 'images/question-only.svg' %}">
                                <figcaption><p>Detalhes</p></figcaption>
                            </figure>
                        </a>
                    </div>
                    <div class="grade">
                        <a href="{% url 't:question-answersgrading' pk=q.pk %}">
                            <figure>
                                <img src="{% static 'images/answers-to-evaluate.svg' %}">
                                <figcaption><p>Avaliar Respostas</p></figcaption>
                            </figure>
                        </a>
                    </div>
                    <div class="answers-list">
                        <a href="{% url 't:answers-list' pk=q.pk %}">
                            <figure>
                                <img src="{% static 'images/answers-3.svg' %}">
                                <figcaption><p>Ver Respostas</p></figcaption>
                            </figure>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <h4 class="paddingtop">Sem questões nessa prova por enquanto.</h4>
    {% endfor %}
    </div>

{% endblock %}

proj/templates/t/teacher_index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static i18n %}

{% block title %}Início{% endblock %}
{% block speccss %}
    <link href="{% static 'css/teacher_index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="row teacher-index-all-options">

        <div class="col-sm-3 teacher-index-options">
            <a href="{% url 't:test-new' %}">
                <figure>
                    <img src="../../static/images/exam-new.svg">
                    <figcaption><h5>Cadastrar Nova Prova</h5></figcaption>
                </figure>
            </a>
        </div>
        <div class="col-sm-3 teacher-index-options">
            <a href="{% url 't:question-new' %}">
                <figure>
                    <img src="../../static/images/question-answer-new.svg">
                    <figcaption><h5>Criar nova questão</h5></figcaption>
                </figure>
            </a>
        </div>
        <div class="col-sm-3 teacher-index-options">
            <a href="{% url 't:test-all-list' %}">
                <figure>
                    <img src="../../static/images/tests-stack.svg">
                    <figcaption><h5>Lista de todas provas</h5></figcaption>
                </figure>
            </a>
        </div>
        <div class="col-sm-3 teacher-index-options">
            <a href="{% url 't:test-list' %}">
                <figure>
                    <img src="../../static/images/tests-stack2.svg">
                    <figcaption><h5>Lista das minhas provas</h5></figcaption>
                </figure>
            </a>
        </div>

    </div>

{% endblock %}

proj/templates/t/test_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Lista de Provas{% endblock %}
{% block speccss %}
    <link href="{% static 'css/test_list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    {% if is_all %}
        <h1 class="h1-styled">Lista de Provas </h1>
    {% else %}
        <h1 class="h1-styled">Lista de Provas criadas por você </h1>
    {% endif %}

    <div class="test-list">
    {% for test in object_list %}
        <div class="row">
            <div class="col-md-8">
                <div class="both-sides">
                    <div class="title-and-description">
                        <h4 class="text-capitalize">{{ test.name }}</h4>
                        <p class="text-capitalize">{{ test.description }}</p>
                        {% if request.user.is_superuser %}
                            <a href="{% url 't:test-update' pk=test.pk %}"><p>Editar</p></a> |
                            <a href="{% url 't:test-delete' pk=test.pk %}"><p>Deletar</p></a>
                        {% endif %}
                    </div>
                    <div class="q-button">
                        <a href="{% url 't:question-list-by-test' pk=test.pk %}">
                            <figure>
                                <img src="{% static 'images/questions-3.svg' %}">
                                <figcaption><p>Ver Questões</p></figcaption>
                            </figure>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <h4 class="paddingtop">Sem provas por enquanto.</h4>
    {% endfor %}
    </div>

{% endblock %}